use [master]
go
-- select * from keyword; -- init 185
go
/*
   drop table if exists keyword;
go
   drop table if exists kw_type;
   drop table if exists kw_source;
*/
go
create table dbo.kw_type(
    constraint pk_keyword_type primary key clustered (id asc)
   ,id int not null 
   ,constraint ak_keyword_type_name unique ([name])
   ,[name] sysname
);
go
insert dbo.kw_type (id,[name])
values(1,'RESERVED'),(2,'NON-RESERVED');
go
create table dbo.kw_source ( 
    constraint pk_keyword_source primary key clustered (id asc)
   ,id int not null identity(1,1)
   ,constraint ak_keyword_source_name unique ([name])
   ,[name] varchar(900) not null 
);
go
create table dbo.keyword ( 
    constraint pk_keyword primary key clustered (word)
   ,word sysname not null 
   ,[type_id] int not null
       constraint fk_keyword_type 
           foreign key 
           references dbo.kw_type(id)
   ,source_id int not null
        constraint fk_keyword_source
            foreign key
            references dbo.kw_source(id)
   ,notes varchar(1000) not null constraint df_keyword_notes default '{}'
);
go
create or alter proc #add_keyword_batch
     @keyword_list varchar(max)
    ,@delimiter varchar(10) = ','
    ,@source sysname
    ,@type   sysname
as
begin
    set nocount on; 
    declare @type_id int
           ,@source_id int
           ,@msg varchar(1000)
           ,@row_count int;

    insert dbo.kw_source ([name])
    select @source
    where not exists ( 
        select 1 
        from dbo.kw_source ks 
        where [name] = @source );

    select @source_id = id 
    from dbo.kw_source ks 
    where [name] = @source;

    select @type_id = id
    from dbo.kw_type 
    where [name] = @type;

    if @type_id is null
    begin
        set @msg ='Specified TYPE of '+isnull(@type,'<NULL>')+' not found.'; 
        raiserror(@msg,11,0);
        return;
    end

    drop table if exists #words;
    create table #words ( word sysname not null primary key );

    insert #words (word)
    select distinct [value]
    from string_split(@keyword_list,@delimiter) ss
    where ss.[value] is not null 
        and ss.[value] <> '';

    update k set
         notes=json_modify(k.notes,'append $.secondary_sources',@source_id)
-- make reserved if not already reserved
        ,source_id = iif(k.source_id=2 and @source_id=1,@source_id,k.source_id) 
    from dbo.keyword k
    join #words w on w.word = k.word
    where k.source_id <> @source_id 
        and not exists ( select 1 
                         from openjson(k.notes,'$.secondary_sources') x
                         where try_cast(x.[value] as int) = @source_id );

    set @row_count = @@rowcount;
    print convert(varchar(10),@row_count)+' word(s) updated with additional source.';

    insert dbo.keyword (word,[type_id],source_id)
    select w.word,@type_id,@source_id
    from #words w
    where not exists ( select 1
                       from dbo.keyword k2 
                       where k2.word = w.word );

   set @row_count = @@rowcount;
   print convert(varchar(10),@row_count)+' word(s) inserted.';

end;
go
declare @words varchar(max);
set @words = 'ADD,EXTERNAL,PROCEDURE,ALL,FETCH,PUBLIC,ALTER,FILE,RAISERROR,AND,FILLFACTOR,READ,ANY,FOR,READTEXT,AS,FOREIGN,RECONFIGURE,ASC,FREETEXT,REFERENCES,AUTHORIZATION,FREETEXTTABLE,REPLICATION,BACKUP,FROM,RESTORE,BEGIN,FULL,RESTRICT,BETWEEN,FUNCTION,RETURN,BREAK,GOTO,REVERT,BROWSE,GRANT,REVOKE,BULK,GROUP,RIGHT,BY,HAVING,ROLLBACK,CASCADE,HOLDLOCK,ROWCOUNT,CASE,IDENTITY,ROWGUIDCOL,CHECK,IDENTITY_INSERT,RULE,CHECKPOINT,IDENTITYCOL,SAVE,CLOSE,IF,SCHEMA,CLUSTERED,IN,SECURITYAUDIT,COALESCE,INDEX,SELECT,COLLATE,INNER,SEMANTICKEYPHRASETABLE,COLUMN,INSERT,SEMANTICSIMILARITYDETAILSTABLE,COMMIT,INTERSECT,SEMANTICSIMILARITYTABLE,COMPUTE,INTO,SESSION_USER,CONSTRAINT,IS,SET,CONTAINS,JOIN,SETUSER,CONTAINSTABLE,KEY,SHUTDOWN,CONTINUE,KILL,SOME,CONVERT,LEFT,STATISTICS,CREATE,LIKE,SYSTEM_USER,CROSS,LINENO,TABLE,CURRENT,LOAD,TABLESAMPLE,CURRENT_DATE,MERGE,TEXTSIZE,CURRENT_TIME,NATIONAL,THEN,CURRENT_TIMESTAMP,NOCHECK,TO,CURRENT_USER,NONCLUSTERED,TOP,CURSOR,NOT,TRAN,DATABASE,NULL,TRANSACTION,DBCC,NULLIF,TRIGGER,DEALLOCATE,OF,TRUNCATE,DECLARE,OFF,TRY_CONVERT,DEFAULT,OFFSETS,TSEQUAL,DELETE,ON,UNION,DENY,OPEN,UNIQUE,DESC,OPENDATASOURCE,UNPIVOT,DISK,OPENQUERY,UPDATE,DISTINCT,OPENROWSET,UPDATETEXT,DISTRIBUTED,OPENXML,USE,DOUBLE,OPTION,USER,DROP,OR,VALUES,DUMP,ORDER,VARYING,ELSE,OUTER,VIEW,END,OVER,WAITFOR,ERRLVL,PERCENT,WHEN,ESCAPE,PIVOT,WHERE,EXCEPT,PLAN,WHILE,EXEC,PRECISION,WITH,EXECUTE,PRIMARY,WITHIN GROUP,EXISTS,PRINT,WRITETEXT,EXIT,PROC';
exec dbo.#add_keyword_batch @keyword_list = @words
   ,@source = 'https://docs.microsoft.com/en-us/sql/t-sql/language-elements/reserved-keywords-transact-sql' 
   ,@type = 'RESERVED'; 
go
declare @words varchar(max);
set @words = 'ABSOLUTE,EXEC,OVERLAPS,ACTION,EXECUTE,PAD,ADA,EXISTS,PARTIAL,ADD,EXTERNAL,PASCAL,ALL,EXTRACT,POSITION,ALLOCATE,FALSE,PRECISION,ALTER,FETCH,PREPARE,AND,FIRST,PRESERVE,ANY,FLOAT,PRIMARY,ARE,FOR,PRIOR,AS,FOREIGN,PRIVILEGES,ASC,FORTRAN,PROCEDURE,ASSERTION,FOUND,PUBLIC,AT,FROM,READ,AUTHORIZATION,FULL,REAL,AVG,GET,REFERENCES,BEGIN,GLOBAL,RELATIVE,BETWEEN,GO,RESTRICT,BIT,GOTO,REVOKE,BIT_LENGTH,GRANT,RIGHT,BOTH,GROUP,ROLLBACK,BY,HAVING,ROWS,CASCADE,HOUR,SCHEMA,CASCADED,IDENTITY,SCROLL,CASE,IMMEDIATE,SECOND,CAST,IN,SECTION,CATALOG,INCLUDE,SELECT,CHAR,INDEX,SESSION,CHAR_LENGTH,INDICATOR,SESSION_USER,CHARACTER,INITIALLY,SET,CHARACTER_LENGTH,INNER,SIZE,CHECK,INPUT,SMALLINT,CLOSE,INSENSITIVE,SOME,COALESCE,INSERT,SPACE,COLLATE,INT,SQL,COLLATION,INTEGER,SQLCA,COLUMN,INTERSECT,SQLCODE,COMMIT,INTERVAL,SQLERROR,CONNECT,INTO,SQLSTATE,CONNECTION,IS,SQLWARNING,CONSTRAINT,ISOLATION,SUBSTRING,CONSTRAINTS,JOIN,SUM,CONTINUE,KEY,SYSTEM_USER,CONVERT,LANGUAGE,TABLE,CORRESPONDING,LAST,TEMPORARY,COUNT,LEADING,THEN,CREATE,LEFT,TIME,CROSS,LEVEL,TIMESTAMP,CURRENT,LIKE,TIMEZONE_HOUR,CURRENT_DATE,LOCAL,TIMEZONE_MINUTE,CURRENT_TIME,LOWER,TO,CURRENT_TIMESTAMP,MATCH,TRAILING,CURRENT_USER,MAX,TRANSACTION,CURSOR,MIN,TRANSLATE,DATE,MINUTE,TRANSLATION,DAY,MODULE,TRIM,DEALLOCATE,MONTH,TRUE,DEC,NAMES,UNION,DECIMAL,NATIONAL,UNIQUE,DECLARE,NATURAL,UNKNOWN,DEFAULT,NCHAR,UPDATE,DEFERRABLE,NEXT,UPPER,DEFERRED,NO,USAGE,DELETE,NONE,USER,DESC,NOT,USING,DESCRIBE,NULL,VALUE,DESCRIPTOR,NULLIF,VALUES,DIAGNOSTICS,NUMERIC,VARCHAR,DISCONNECT,OCTET_LENGTH,VARYING,DISTINCT,OF,VIEW,DOMAIN,ON,WHEN,DOUBLE,ONLY,WHENEVER,DROP,OPEN,WHERE,ELSE,OPTION,WITH,END,OR,WORK,END-EXEC,ORDER,WRITE,ESCAPE,OUTER,YEAR,EXCEPT,OUTPUT,ZONE,EXCEPTION'
exec dbo.#add_keyword_batch @keyword_list = @words
   ,@source='https://docs.microsoft.com/en-us/sql/t-sql/language-elements/reserved-keywords-transact-sql#odbc-reserved-keywords'
   ,@type='RESERVED';
go
declare @words varchar(max);
set @words = 'ABSOLUTE,HOST,RELATIVE,ACTION,HOUR,RELEASE,ADMIN,IGNORE,RESULT,AFTER,IMMEDIATE,RETURNS,AGGREGATE,INDICATOR,ROLE,ALIAS,INITIALIZE,ROLLUP,ALLOCATE,INITIALLY,ROUTINE,ARE,INOUT,ROW,ARRAY,INPUT,ROWS,ASENSITIVE,INT,SAVEPOINT,ASSERTION,INTEGER,SCROLL,ASYMMETRIC,INTERSECTION,SCOPE,AT,INTERVAL,SEARCH,ATOMIC,ISOLATION,SECOND,BEFORE,ITERATE,SECTION,BINARY,LANGUAGE,SENSITIVE,BIT,LARGE,SEQUENCE,BLOB,LAST,SESSION,BOOLEAN,LATERAL,SETS,BOTH,LEADING,SIMILAR,BREADTH,LESS,SIZE,CALL,LEVEL,SMALLINT,CALLED,LIKE_REGEX,SPACE,CARDINALITY,LIMIT,SPECIFIC,CASCADED,LN,SPECIFICTYPE,CAST,LOCAL,SQL,CATALOG,LOCALTIME,SQLEXCEPTION,CHAR,LOCALTIMESTAMP,SQLSTATE,CHARACTER,LOCATOR,SQLWARNING,CLASS,MAP,START,CLOB,MATCH,STATE,COLLATION,MEMBER,STATEMENT,COLLECT,METHOD,STATIC,COMPLETION,MINUTE,STDDEV_POP,CONDITION,MOD,STDDEV_SAMP,CONNECT,MODIFIES,STRUCTURE,CONNECTION,MODIFY,SUBMULTISET,CONSTRAINTS,MODULE,SUBSTRING_REGEX,CONSTRUCTOR,MONTH,SYMMETRIC,CORR,MULTISET,SYSTEM,CORRESPONDING,NAMES,TEMPORARY,COVAR_POP,NATURAL,TERMINATE,COVAR_SAMP,NCHAR,THAN,CUBE,NCLOB,TIME,CUME_DIST,NEW,TIMESTAMP,CURRENT_CATALOG,NEXT,TIMEZONE_HOUR,CURRENT_DEFAULT_TRANSFORM_GROUP,NO,TIMEZONE_MINUTE,CURRENT_PATH,NONE,TRAILING,CURRENT_ROLE,NORMALIZE,TRANSLATE_REGEX,CURRENT_SCHEMA,NUMERIC,TRANSLATION,CURRENT_TRANSFORM_GROUP_FOR_TYPE,OBJECT,TREAT,CYCLE,OCCURRENCES_REGEX,TRUE,DATA,OLD,UESCAPE,DATE,ONLY,UNDER,DAY,OPERATION,UNKNOWN,DEC,ORDINALITY,UNNEST,DECIMAL,OUT,USAGE,DEFERRABLE,OVERLAY,USING,DEFERRED,OUTPUT,VALUE,DEPTH,PAD,VAR_POP,DEREF,PARAMETER,VAR_SAMP,DESCRIBE,PARAMETERS,VARCHAR,DESCRIPTOR,PARTIAL,VARIABLE,DESTROY,PARTITION,WHENEVER,DESTRUCTOR,PATH,WIDTH_BUCKET,DETERMINISTIC,POSTFIX,WITHOUT,DICTIONARY,PREFIX,WINDOW,DIAGNOSTICS,PREORDER,WITHIN,DISCONNECT,PREPARE,WORK,DOMAIN,PERCENT_RANK,WRITE,DYNAMIC,PERCENTILE_CONT,XMLAGG,EACH,PERCENTILE_DISC,XMLATTRIBUTES,ELEMENT,POSITION_REGEX,XMLBINARY,END-EXEC,PRESERVE,XMLCAST,EQUALS,PRIOR,XMLCOMMENT,EVERY,PRIVILEGES,XMLCONCAT,EXCEPTION,RANGE,XMLDOCUMENT,FALSE,READS,XMLELEMENT,FILTER,REAL,XMLEXISTS,FIRST,RECURSIVE,XMLFOREST,FLOAT,REF,XMLITERATE,FOUND,REFERENCING,XMLNAMESPACES,FREE,REGR_AVGX,XMLPARSE,FULLTEXTTABLE,REGR_AVGY,XMLPI,FUSION,REGR_COUNT,XMLQUERY,GENERAL,REGR_INTERCEPT,XMLSERIALIZE,GET,REGR_R2,XMLTABLE,GLOBAL,REGR_SLOPE,XMLTEXT,GO,REGR_SXX,XMLVALIDATE,GROUPING,REGR_SXY,YEAR,HOLD,REGR_SYY,ZONE'
exec dbo.#add_keyword_batch @keyword_list = @words
   ,@source='https://docs.microsoft.com/en-us/sql/t-sql/language-elements/reserved-keywords-transact-sql#future-keywords'
   ,@type='RESERVED';
go
declare @words varchar(max);
set @words = 'ABSOLUTE,ACTION,ADD,ADMIN,AFTER,AGGREGATE,ALIAS,ALL,ALLOCATE,ALLOWED,ALTER,AND,ANY,ARE,ARRAY,AS,ASC,ASSERTION,AT,AUTHORIZATION,BEFORE,BEGIN,BINARY,BIT,BLOB,BOOLEAN,BOTH,BREADTH,BY,CALL,CASCADE,CASCADED,CASE,CAST,CATALOG,CHAR,CHARACTER,CHECK,CLASS,CLOB,CLOSE,COLLATE,COLLATION,COLUMN,COMMIT,COMPLETION,CONNECT,CONNECTION,CONSTRAINT,CONSTRAINTS,CONSTRUCTOR,CONTINUE,CORRESPONDING,CREATE,CROSS,CUBE,CURRENT,CURRENT_DATE,CURRENT_PATH,CURRENT_ROLE,CURRENT_TIME,CURRENT_TIMESTAMP,CURRENT_USER,CURSOR,CYCLE,DATA,DATE,DAY,DEALLOCATE,DEC,DECIMAL,DECLARE,DEFAULT,DEFERRABLE,DEFERRED,DELETE,DEPTH,DEREF,DESC,DESCRIBE,DESCRIPTOR,DESTROY,DESTRUCTOR,DETERMINISTIC,DIAGNOSTICS,DICTIONARY,DISCONNECT,DISTINCT,DOMAIN,DOUBLE,DROP,DYNAMIC,EACH,ELSE,END_EXEC,END,EQUALS,ESCAPE,EVERY,EXCEPT,EXCEPTION,EXEC,EXECUTE,EXTERNAL,FALSE,FENCED,FETCH,FINAL,FIRST,FLOAT,FOR,FOREIGN,FOUND,FREE,FROM,FULL,FUNCTION,GENERAL,GET,GLOBAL,GO,GOTO,GRANT,GROUP,GROUPING,HAVING,HOST,HOUR,IDENTITY,IGNORE,IMMEDIATE,IN,INDICATOR,INITIALIZE,INITIALLY,INNER,INOUT,INPUT,INSERT,INT,INTEGER,INTERSECT,INTERVAL,INTO,IS,ISOLATION,ITERATE,JOIN,KEY,LANGUAGE,LARGE,LAST,LATERAL,LEADING,LEFT,LESS,LEVEL,LIKE,LIMIT,LOCAL,LOCALTIME,LOCALTIMESTAMP,LOCATOR,MAP,MATCH,MINUTE,MODIFIES,MODIFY,MODULE,MONTH,NAMES,NATIONAL,NATURAL,NCHAR,NCLOB,NEW,NEXT,NO,NONE,NOT,NULL,NUMERIC,OBJECT,OF,OFF,OLD,ON,ONLY,OPEN,OPERATION,OPTION,OR,ORDER,ORDINALITY,OUT,OUTER,OUTPUT,PAD,PARALLEL,PARAMETER,PARAMETERS,PARTIAL,PATH,POSTFIX,PRECISION,PREFIX,PREORDER,PREPARE,PRESERVE,PRIMARY,PRIOR,PRIVILEGES,PROCEDURE,PUBLIC,READ,READS,REAL,RECURSIVE,REF,REFERENCES,REFERENCING,RELATIVE,RESTRICT,RESULT,RETURN,RETURNS,REVOKE,RIGHT,ROLE,ROLLBACK,ROLLUP,ROUTINE,ROW,ROWS,SAVEPOINT,SCHEMA,SCOPE,SCROLL,SEARCH,SECOND,SECTION,SELECT,SEQUENCE,SESSION,SESSION_USER,SET,SETS,SIZE,SMALLINT,SOME,SPACE,SPECIFIC,SPECIFICTYPE,SQL,SQLEXCEPTION,SQLSTATE,SQLWARNING,START,STATE,STATEMENT,STATIC,STRUCTURE,SYSTEM_USER,TABLE,TEMPORARY,TERMINATE,THAN,THEN,TIME,TIMESTAMP,TIMEZONE_HOUR,TIMEZONE_MINUTE,TO,TRAILING,TRANSACTION,TRANSLATION,TREAT,TRIGGER,TRUE,UNDER,UNION,UNIQUE,UNKNOWN,UNNEST,UPDATE,USAGE,USER,USING,VALUE,VALUES,VARCHAR,VARIABLE,VARYING,VIEW,WHEN,WHENEVER,WHERE,WITH,WITHOUT,WORK,WRITE,YEAR,ZONE'
exec dbo.#add_keyword_batch @keyword_list = @words
   ,@source='https://www.ibm.com/support/knowledgecenter/en/SSULQD_7.0.3/com.ibm.nz.dbu.doc/r_dbuser_nonreserved_keywords.html'
   ,@type='NON-RESERVED';
go
declare @words varchar(max);
set @words = 'ABORT,DEC,LEADING,RESET,ADMIN,DECIMAL,LEFT,REUSE,AGGREGATE,DECODE,LIKE,RIGHT,ALIGN,DEFAULT,LIMIT,ROWS,ALL,DEFERRABLE,LISTEN,ROWSETLIMIT,ALLOCATE,DESC,LOAD,RULE,ANALYSE,DISTINCT,LOCAL,SEARCH,ANALYZE,DISTRIBUTE,LOCK,SELECT,AND,DO,MATERIALIZED,SEQUENCE,ANY,ELSE,MINUS,SESSION_USER,AS,END,MOVE,SETOF,ASC,EXCEPT,NATURAL,SHOW,BETWEEN,EXCLUDE,NCHAR,SOME,BINARY,EXISTS,NEW,SUBSTRING,BIT,EXPLAIN,NOT,SYSTEM,BOTH,EXPRESS,NOTNULL,TABLE,CASE,EXTEND,NULL,THEN,CAST,EXTERNAL,NULLIF,TIES,CHAR,EXTRACT,NULLS,TIME,CHARACTER,FALSE,NUMERIC,TIMESTAMP,CHECK,FIRST,NVL,TO,CLUSTER,FLOAT,NVL2,TRAILING,COALESCE,FOLLOWING,OFF,TRANSACTION,COLLATE,FOR,OFFSET,TRIGGER,COLLATION,FOREIGN,OLD,TRIM,COLUMN,FROM,ON,TRUE,CONSTRAINT,FULL,ONLINE,UNBOUNDED,COPY,FUNCTION,ONLY,UNION,CROSS,GENSTATS,OR,UNIQUE,CURRENT,GLOBAL,ORDER,USER,CURRENT_CATALOG,GROUP,OTHERS,USING,CURRENT_DATE,HAVING,OUT,VACUUM,CURRENT_DB,IDENTIFIER_CASE,OUTER,VARCHAR,CURRENT_SCHEMA,ILIKE,OVER,VERBOSE,CURRENT_SID,IN,OVERLAPS,VERSION,CURRENT_TIME,INDEX,PARTITION,VIEW,CURRENT_TIMESTAMP,INITIALLY,POSITION,WHEN,CURRENT_USER,INNER,PRECEDING,WHERE,CURRENT_USERID,INOUT,PRECISION,WITH,CURRENT_USEROID,INTERSECT,PRESERVE,WRITE,DEALLOCATE,INTERVAL,PRIMARY,RESET, ,INTO, ,REUSE'
exec dbo.#add_keyword_batch @keyword_list = @words
   ,@source='https://www.ibm.com/support/knowledgecenter/SSULQD_7.0.3/com.ibm.nz.dbu.doc/r_dbuser_sql_common_reserved_words.html'
   ,@type='RESERVED';
exec dbo.#add_keyword_batch @keyword_list = 'CTID,OID,XMIN,CMIN,XMAX,CMAX,TABLEOID,ROWID,DATASLICEID,CREATEXID,DELETEXID'
    ,@source='https://www.ibm.com/support/knowledgecenter/SSULQD_7.0.3/com.ibm.nz.dbu.doc/r_dbuser_sql_common_reserved_words.html'
   ,@type='RESERVED';
go
declare @words varchar(max);
set @words = 'ASCII,CHAR,CHARINDEX,CONCAT,Concat with +,DATALENGTH,LEFT,LEN,LOWER,LTRIM,NCHAR,PATINDEX,REPLACE,RIGHT,RTRIM,SPACE,STR,STUFF,SUBSTRING,UPPER,ABS,AVG,CEILING,COUNT,FLOOR,MAX,MIN,RAND,ROUND,SIGN,SUM,CURRENT_TIMESTAMP,DATEADD,DATEDIFF,DATENAME,DATEPART,DAY,GETDATE,GETUTCDATE,MONTH,YEAR,CAST,CONVERT,CASE,COALESCE,CURRENT_USER,ISDATE,ISNULL,ISNUMERIC,LAG,LEAD,NULLIF,SESSION_USER,SESSIONPROPERTY,SYSTEM_USER,USER_NAME'
exec dbo.#add_keyword_batch @keyword_list = @words
   ,@source='https://www.techonthenet.com/sql_server/functions/index.php'
   ,@type='NON-RESERVED';
go
exec dbo.#add_keyword_batch 
    @keyword_list='AVG,MIN,CHECKSUM_AGG,SUM,COUNT,STDEV,COUNT_BIG,STDEVP,GROUPING,STRING_AGG,GROUPING_ID,VAR,MAX,VARP'  
   ,@source='https://docs.microsoft.com/en-us/sql/t-sql/functions/aggregate-functions-transact-sql'
   ,@type='NON-RESERVED'
exec dbo.#add_keyword_batch 
    @keyword_list='CUME_DIST,LEAD,FIRST_VALUE,PERCENTILE_CONT,LAG,PERCENTILE_DISC,LAST_VALUE,PERCENT_RANK'  
   ,@source='https://docs.microsoft.com/en-us/sql/t-sql/functions/analytic-functions-transact-sql'
   ,@type='NON-RESERVED'
exec dbo.#add_keyword_batch 
    @keyword_list='TERTIARY_WEIGHTS'  
   ,@source='https://docs.microsoft.com/en-us/sql/t-sql/functions/collation-functions-tertiary-weights-transact-sql'
   ,@type='NON-RESERVED'
exec dbo.#add_keyword_batch 
    @keyword_list='COLLATIONPROPERTY'  
   ,@source='https://docs.microsoft.com/en-us/sql/t-sql/functions/collation-functions-collationproperty-transact-sql'
   ,@type='NON-RESERVED'
exec dbo.#add_keyword_batch 
    @keyword_list='@@DATEFIRST,@@OPTIONS,@@DBTS,@@REMSERVER,@@LANGID,@@SERVERNAME,@@LANGUAGE,@@SERVICENAME,@@LOCK_TIMEOUT,@@SPID,@@MAX_CONNECTIONS,@@TEXTSIZE,@@MAX_PRECISION,@@VERSION,@@NESTLEVEL'  
   ,@source='https://docs.microsoft.com/en-us/sql/t-sql/functions/configuration-functions-transact-sql'
   ,@type='NON-RESERVED'
exec dbo.#add_keyword_batch 
    @keyword_list='CAST,CONVERT,PARSE,TRY_CAST,TRY_CONVERT,TRY_PARSE' 
   ,@source='https://docs.microsoft.com/en-us/sql/t-sql/functions/conversion-functions-transact-sql'
   ,@type='NON-RESERVED'
exec dbo.#add_keyword_batch 
    @keyword_list='ENCRYPTBYKEY,DECRYPTBYKEY,ENCRYPTBYPASSPHRASE,DECRYPTBYPASSPHRASE,KEY_ID,KEY_GUID,DECRYPTBYKEYAUTOASYMKEY,KEY_NAME,SYMKEYPROPERTY,ENCRYPTBYASYMKEY,DECRYPTBYASYMKEY,ENCRYPTBYCert,DECRYPTBYCERT,ASYMKEYPROPERTY,ASYMKEY_ID,SIGNBYASYMKEY,VERIFYSIGNEDBYASMKEY,SIGNBYCERT,VERIGYSIGNEDBYCERT,IS_OBJECTSIGNED,DecryptByKeyAutoCert,HASHBYTES,CERTENCODED,CERTPRIVATEKEY'  
   ,@source='https://docs.microsoft.com/en-us/sql/t-sql/functions/cryptographic-functions-transact-sql'
   ,@type='NON-RESERVED'
exec dbo.#add_keyword_batch 
    @keyword_list='@@CURSOR_ROWS,CURSOR_STATUS,@@FETCH_STATUS'  
   ,@source='https://docs.microsoft.com/en-us/sql/t-sql/functions/cursor-functions-transact-sql'
   ,@type='NON-RESERVED'
exec dbo.#add_keyword_batch 
    @keyword_list='DATALENGTH,IDENT_SEED,IDENT_CURRENT,IDENTITY,IDENT_INCR,SQL_VARIANT_PROPERTY'  
   ,@source='https://docs.microsoft.com/en-us/sql/t-sql/functions/data-type-functions-transact-sql'
   ,@type='NON-RESERVED'
exec dbo.#add_keyword_batch 
    @keyword_list='@@DATEFIRST,CURRENT_TIMESTAMP,DATEADD,DATEDIFF,DATEDIFF_BIG,DATEFROMPARTS,DATENAME,DATEPART,DATETIME2FROMPARTS,DATETIMEFROMPARTS,DATETIMEOFFSETFROMPARTS,DAY,EOMONTH,GETDATE,GETUTCDATE,ISDATE,MONTH,SMALLDATETIMEFROMPARTS,SWITCHOFFSET,SYSDATETIME,SYSDATETIMEOFFSET,SYSUTCDATETIME,TIMEFROMPARTS,TODATETIMEOFFSET,YEAR'  
   ,@source='https://docs.microsoft.com/en-us/sql/t-sql/functions/date-and-time-data-types-and-functions-transact-sql'
   ,@type='NON-RESERVED'
exec dbo.#add_keyword_batch 
    @keyword_list='ISJSON,JSON_VALUE,JSON_QUERY,JSON_MODIFY'  
   ,@source='https://docs.microsoft.com/en-us/sql/t-sql/functions/json-functions-transact-sql'
   ,@type='NON-RESERVED'
exec dbo.#add_keyword_batch 
    @keyword_list='ABS,ACOS,ASIN,ATAN,ATN2,CEILING,COS,COT,DEGREES,EXP,FLOOR,LOG,LOG10,PI,POWER,RADIANS,RAND,ROUND,SIGN,SIN,SQRT,SQUARE,TAN'  
   ,@source='https://docs.microsoft.com/en-us/sql/t-sql/functions/mathematical-functions-transact-sql'
   ,@type='NON-RESERVED'
exec dbo.#add_keyword_batch 
    @keyword_list='CHOOSE'  
   ,@source='https://docs.microsoft.com/en-us/sql/t-sql/functions/logical-functions-choose-transact-sql'
   ,@type='NON-RESERVED'
exec dbo.#add_keyword_batch 
    @keyword_list='IIF'  
   ,@source='https://docs.microsoft.com/en-us/sql/t-sql/functions/logical-functions-iif-transact-sql'
   ,@type='NON-RESERVED'
exec dbo.#add_keyword_batch 
    @keyword_list='@@PROCID,APP_NAME,APPLOCK_MODE,APPLOCK_TEST,ASSEMBLYPROPERTY,COL_LENGTH,COL_NAME,COLUMNPROPERTY,DATABASE_PRINCIPAL_ID,DATABASEPROPERTYEX,DB_ID,DB_NAME,FILE_ID,FILE_IDEX,FILE_NAME,FILEGROUP_ID,FILEGROUP_NAME,FILEGROUPPROPERTY,FILEPROPERTY,FULLTEXTCATALOGPROPERTY,FULLTEXTSERVICEPROPERTY,INDEX_COL,INDEXKEY_PROPERTY,INDEXPROPERTY,NEXT VALUE FOR,OBJECT_DEFINITION,OBJECT_ID,OBJECT_NAME,OBJECT_SCHEMA_NAME,OBJECTPROPERTY,OBJECTPROPERTYEX,ORIGINAL_DB_NAME,PARSENAME,SCHEMA_ID,SCHEMA_NAME,SCOPE_IDENTITY,SERVERPROPERTY,STATS_DATE,TYPE_ID,TYPE_NAME,TYPEPROPERTY,VERSION'  
   ,@source='https://docs.microsoft.com/en-us/sql/t-sql/functions/metadata-functions-transact-sql'
   ,@type='NON-RESERVED'
exec dbo.#add_keyword_batch 
    @keyword_list='BIT_LENGTH,CONCAT,OCTET_LENGTH,TRUNCATE,CURRENT_DATE,CURDATE,CURRENT_TIME,CURTIME,DAYNAME,DAYOFMONTH,DAYOFWEEK,HOUR,MINUTE,SECOND,MONTHNAME,QUARTER,WEEK'  
   ,@source='https://docs.microsoft.com/en-us/sql/t-sql/functions/odbc-scalar-functions-transact-sql'
   ,@type='NON-RESERVED'
exec dbo.#add_keyword_batch
     @keyword_list='DENSE_RANK,NTILE,RANK,ROW_NUMBER'
    ,@source='https://docs.microsoft.com/en-us/sql/t-sql/functions/ranking-functions-transact-sql'
    ,@type='NON-RESERVED'
exec dbo.#add_keyword_batch
     @keyword_list='PUBLISHINGSERVERNAME'
    ,@source='https://docs.microsoft.com/en-us/sql/t-sql/functions/replication-functions-publishingservername'
    ,@type='NON-RESERVED'
exec dbo.#add_keyword_batch
     @keyword_list='OPENDATASOURCE,OPENJSON,OPENROWSET,OPENQUERY,OPENXML'
    ,@source='https://docs.microsoft.com/en-us/sql/t-sql/functions/rowset-functions-transact-sql'
    ,@type='NON-RESERVED'
exec dbo.#add_keyword_batch
     @keyword_list='CERTENCODED,PWDCOMPARE,CERTPRIVATEKEY,PWDENCRYPT,CURRENT_USER,SCHEMA_ID,DATABASE_PRINCIPAL_ID,SCHEMA_NAME,fn_builtin_permissions,SESSION_USER,fn_get_audit_file,SUSER_ID,fn_my_permissions,SUSER_SID,HAS_PERMS_BY_NAME,SUSER_SNAME,IS_MEMBER,SYSTEM_USER,IS_ROLEMEMBER,SUSER_NAME,IS_SRVROLEMEMBER,USER_ID,ORIGINAL_LOGIN,USER_NAME,PERMISSIONS'
    ,@source='https://docs.microsoft.com/en-us/sql/t-sql/functions/security-functions-transact-sql'
    ,@type='NON-RESERVED'
exec dbo.#add_keyword_batch
     @keyword_list='ASCII,CHAR,CHARINDEX,CONCAT,CONCAT_WS,DIFFERENCE,FORMAT,LEFT,LEN,LOWER,LTRIM,NCHAR,PATINDEX,QUOTENAME,REPLACE,REPLICATE,REVERSE,RIGHT,RTRIM,SOUNDEX,SPACE,STR,STRING_AGG,STRING_ESCAPE,STRING_SPLIT,STUFF,SUBSTRING,TRANSLATE,TRIM,UNICODE,UPPER'
    ,@source='https://docs.microsoft.com/en-us/sql/t-sql/functions/string-functions-transact-sql'
    ,@type='NON-RESERVED'
exec dbo.#add_keyword_batch
     @keyword_list='$PARTITION,@@ERROR,@@IDENTITY,@@PACK_RECEIVED,@@ROWCOUNT,@@TRANCOUNT,BINARY_CHECKSUM,CHECKSUM,COMPRESS,CONNECTIONPROPERTY,CONTEXT_INFO,CURRENT_REQUEST_ID,CURRENT_TRANSACTION_ID,DECOMPRESS,ERROR_LINE,ERROR_MESSAGE,ERROR_NUMBER,ERROR_PROCEDURE,ERROR_SEVERITY,ERROR_STATE,FORMATMESSAGE,GET_FILESTREAM_TRANSACTION_CONTEXT,GETANSINULL,HOST_ID,HOST_NAME,ISNULL,ISNUMERIC,MIN_ACTIVE_ROWVERSION,NEWID,NEWSEQUENTIALID,ROWCOUNT_BIG,SESSION_CONTEXT,SESSION_ID,XACT_STATE'
    ,@source='https://docs.microsoft.com/en-us/sql/t-sql/functions/system-functions-transact-sql'
    ,@type='NON-RESERVED'
exec dbo.#add_keyword_batch
     @keyword_list='@@CONNECTIONS,@@CPU_BUSY,@@IDLE,@@IO_BUSY,@@PACK_SENT,@@PACKET_ERRORS,@@TIMETICKS,@@TOTAL_ERRORS,@@TOTAL_READ,@@TOTAL_WRITE'
    ,@source='https://docs.microsoft.com/en-us/sql/t-sql/functions/system-functions-transact-sql'
    ,@type='NON-RESERVED'
exec dbo.#add_keyword_batch
     @keyword_list='TEXTPTR'
    ,@source='https://docs.microsoft.com/en-us/sql/t-sql/functions/text-and-image-functions-textptr-transact-sql'
    ,@type='NON-RESERVED'
exec dbo.#add_keyword_batch
     @keyword_list='TEXTVALID'
    ,@source='https://docs.microsoft.com/en-us/sql/t-sql/functions/text-and-image-functions-textvalid-transact-sql'
    ,@type='NON-RESERVED'
exec dbo.#add_keyword_batch
     @keyword_list='COLUMNS_UPDATED,EVENTDATA,TRIGGER_NESTLEVEL,UPDATE'
    ,@source='https://docs.microsoft.com/en-us/sql/t-sql/functions/trigger-functions-transact-sql'
    ,@type='NON-RESERVED'
exec dbo.#add_keyword_batch
     @keyword_list='bigint,numeric,bit,smallint,decimal,smallmoney,int,tinyint,money,float,real,date,datetimeoffset,datetime2,smalldatetime,datetime,time,char,varchar,text,nchar,nvarchar,ntext,binary,varbinary,image,cursor,rowversion,hierarchyid,uniqueidentifier,sql_variant,xml,table'
    ,@source='https://docs.microsoft.com/en-us/sql/t-sql/data-types/data-types-transact-sql'
    ,@type='NON-RESERVED'
exec dbo.#add_keyword_batch
     @keyword_list='geometry'
    ,@source='https://docs.microsoft.com/en-us/sql/t-sql/spatial-geometry/spatial-types-geometry-transact-sql'
    ,@type='NON-RESERVED'
exec dbo.#add_keyword_batch
     @keyword_list='geography'
    ,@source='https://docs.microsoft.com/en-us/sql/t-sql/spatial-geography/spatial-types-geography'
    ,@type='NON-RESERVED'
exec dbo.#add_keyword_batch
     @keyword_list=''
    ,@source=''
    ,@type='NON-RESERVED'
exec dbo.#add_keyword_batch
     @keyword_list='Application,Event,Address,Name,Status'
    ,@source='mark_1_eyeballs'
    ,@type='NON-RESERVED'
/*
exec dbo.#add_keyword_batch
     @keyword_list=''
    ,@source=''
    ,@type='NON-RESERVED'
*/
go
-- manual review of the list reveals many words T-SQL does not flag for coloration
alter table keyword add is_excluded bit;
go
update keyword set is_excluded = 0;
alter table keyword alter column is_excluded bit not null;
go
declare @excludes varchar(max);
set @excludes='ADA,ALIAS,ALIGN,ALLOCATE,ALLOWED,ANALYSE,ANALYZE,ARE,ARRAY,ASENSITIVE,ASSERTION,BLOB,BOOLEAN,BOTH,BREADTH,CALLED,CARDINALITY,CASCADED,CHAR_LENGTH,CHARACTER_LENGTH,CLASS,CLOB,CLUSTER,CMAX,CMIN,COLLATION,COLLECT,COMPLETION,CONDITION,CONNECTION,CONSTRAINTS,CONSTRUCTOR,CORR,CORRESPONDING,COVAR_POP,COVAR_SAMP,CREATEXID,CTID,CUME_DIST,CURRENT_CATALOG,CURRENT_DB,CURRENT_DEFAULT_TRANSFORM_GROUP,CURRENT_PATH,CURRENT_ROLE,CURRENT_SCHEMA,CURRENT_SID,CURRENT_TRANSFORM_GROUP_FOR_TYPE,CURRENT_USERID,CURRENT_USEROID,CYCLE,DATASLICEID,DECODE,DEFERRABLE,DEFERRED,DELETEXID,DEPTH,DEREF,DESCRIBE,DESCRIPTOR,DESTROY,DESTRUCTOR,DETERMINISTIC,DIAGNOSTICS,DICTIONARY,DISCONNECT,DISTRIBUTE,DO,DOMAIN,EACH,ELEMENT,END_EXEC,EQUALS,EVERY,EXCEPTION,EXCLUDE,EXPLAIN,EXPRESS,EXTEND,FALSE,FENCED,FINAL,FIRST_VALUE,fn_get_audit_file,FORTRAN,FOUND,FREE,FULLTEXTTABLE,FUSION,GENERAL,GENSTATS,HOLD,HOST,IDENTIFIER_CASE,IGNORE,ILIKE,INDICATOR,INITIALIZE,INITIALLY,INOUT,INPUT,INTERSECTION,INTERVAL,LAG,LARGE,LAST_VALUE,LATERAL,LEAD,LEADING,LESS,LIKE_REGEX,LIMIT,LISTEN,LN,LOCALTIME,LOCALTIMESTAMP,LOCATOR,LOCK,MAP,MATERIALIZED,MEMBER,METHOD,MINUS,MODIFIES,MODULE,MULTISET,NAMES,NATURAL,NCLOB,NEW,NOTNULL,NULLS,NVL,NVL2,OCCURRENCES_REGEX,OFFSET,OID,OLD,ONLY,OPERATION,ORDINALITY,OTHERS,OVERLAPS,OVERLAY,PAD,PARALLEL,PARAMETER,PASCAL,PERCENT_RANK,PERCENTILE_CONT,PERCENTILE_DISC,POSITION,POSITION_REGEX,POSTFIX,PREFIX,PREORDER,PREPARE,PRESERVE,PRIVILEGES,READS,REF,REFERENCING,REGR_AVGX,REGR_AVGY,REGR_COUNT,REGR_INTERCEPT,REGR_R2,REGR_SLOPE,REGR_SXX,REGR_SXY,REGR_SYY,RELEASE,RESULT,REUSE,ROUTINE,ROWID,ROWSETLIMIT,SAVEPOINT,SCOPE,SEARCH,SECTION,SENSITIVE,SESSION_ID,SETOF,SHOW,SIMILAR,SIZE,SPECIFIC,SPECIFICTYPE,SQLCA,SQLCODE,SQLERROR,SQLEXCEPTION,SQLSTATE,SQLWARNING,STDDEV_POP,STDDEV_SAMP,STRUCTURE,SUBMULTISET,SUBSTRING_REGEX,TABLEOID,TEMPORARY,TERMINATE,THAN,TIES,TIMEZONE_HOUR,TIMEZONE_MINUTE,TRAILING,TRANSLATE,TRANSLATE_REGEX,TRANSLATION,TREAT,TRUE,UESCAPE,UNDER,UNKNOWN,UNNEST,USAGE,VACUUM,VAR_POP,VAR_SAMP,VARIABLE,VERIGYSIGNEDBYCERT,WHENEVER,WIDTH_BUCKET,WINDOW,WORK,WRITE,XMAX,XMIN,XMLAGG,XMLATTRIBUTES,XMLBINARY,XMLCAST,XMLCOMMENT,XMLCONCAT,XMLDOCUMENT,XMLELEMENT,XMLEXISTS,XMLFOREST,XMLITERATE,XMLNAMESPACES,XMLPARSE,XMLPI,XMLQUERY,XMLSERIALIZE,XMLTABLE,XMLTEXT,XMLVALIDATE';
with excludes as (
    select * 
    from keyword k
    where exists ( select 1 
                   from string_split(@excludes,',') x
                   where x.[value] = k.word )
) -- select * from excludes;
update excludes set 
    is_excluded = 1;
go
select * from dbo.keyword;
go
create or alter view dbo.color_words
as
select lower(word) as word
from keyword 
where is_excluded=0;
go
